server:
  port : 5051
  servlet:
    context-path : /access-control

gotech:
  base_url: localhost:5051

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #to resolve error related to swagger
